### ISSUE TITLE
Make peppolnext app easier to install

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/peppol-php#120]
@Triantafullenia-Doumani just mentioned we should make it easier for people to install the peppolnext app.

Can we add it to the Nextcloud app store?

**Comment by navid-dada** [comment]
adding app into next cloud app has its own process, and I think our product is not complete and functional until now, putting it on market as an incomplete product is not align with nextcoud  community principal

**Comment by michielbdejong** [comment]
OK, agreed. Let's keep the current flow for now (see also the branch I created today for https://github.com/pondersource/peppol-php/issues/121 ) and then once it's all ready for end-users, we know the installation will become easier.
