### ISSUE TITLE
option to accept only SMP-identified senders or also self-hosted ID's [1][2]

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/peppol-php#140]

**Comment by yasharpm** [comment]
1. Self-hosted IDs as in peppolnext users on this nextcloud server or as4 direct?
2. SMP-identified senders automatically means received via LetsPeppol. Is that right?

**Comment by michielbdejong** [comment]
> Self-hosted IDs as in peppolnext users on this nextcloud server or as4 direct?

Self-hosted IDs as in as4 direct identities.
There can be only one peppolnext user per Nextcloud server.

> SMP-identified senders automatically means received via LetsPeppol. Is that right?

Yes.

**Comment by yasharpm** [comment]
> There can be only one peppolnext user per Nextcloud server.

It is possible to have multiple users on a single instance of Nextcloud afaik. My assumption is (and is not actually difficult) that any number of them might install peppolnext and they should not experience conflicts.

**Comment by yasharpm** [comment]
The message is either coming via the as4 direct or letspeppol. Either way, the message always contains a recipient peppol Id. In case of as4 direct, we can assign a UUID which will be shared with the sender. So using the Id, we can always figure out the recipient or reject the message.

**Comment by michielbdejong** [comment]
OK, yes, that would work!

**Comment by yasharpm** [comment]
I implemented LetsPeppol and AS4 Direct sections in the settings. Each one has a button that by clicking on it, user can obtain an identity for. This automatically follows that the user can send invoices and receive bills through either of the available identities.
Changes are in [this](https://github.com/pondersource/peppol-php/commit/a7ed616e8df920daa350a46290245d1822fc1d93) commit.
