### ISSUE TITLE
Which fields to include for an invoice

### ISSUE THREAD

**Issue by yasharpm** [pondersource/peppol-php#154]
Peppol invoices are extensive models that include many fields. For the sake of saving time, I want to put as few fields in the UI as possible.

So, here are the absolute minimum required fields as are required by the invoice definition [here](https://docs.peppol.eu/poacc/billing/3.0/syntax/ubl-invoice/tree/):
- cbc:ID - Invoice number
- cbc:IssueDate - Invoice issue date
- cbc:InvoiceTypeCode - Invoice type code
- cbc:DocumentCurrencyCode - Invoice currency code
- cac:AccountingSupplierParty - SELLER
  - cac:Party - PARTY
    - cbc:EndpointID - Seller electronic address
    - cac:PostalAddress - SELLER POSTAL ADDRESS
    - cac:PartyLegalEntity - PARTY LEGAL ENTITY
      - cbc:RegistrationName - Seller name
- cac:AccountingCustomerParty - BUYER
  - cac:Party - PARTY
    - cbc:EndpointID - Buyer electronic address
    - cac:PostalAddress - BUYER POSTAL ADDRESS
    - cac:PartyLegalEntity - PARTY LEGAL ENTITY
      - cbc:RegistrationName - Buyer name
- cac:TaxTotal - TAX TOTAL
  - cbc:TaxAmount - Invoice total VAT amount, Invoice total VAT amount in accounting currency
- cac:LegalMonetaryTotal - DOCUMENT TOTALS
  - cbc:LineExtensionAmount - Sum of Invoice line net amount
  - cbc:TaxExclusiveAmount - Invoice total amount without VAT
  - cbc:TaxInclusiveAmount - Invoice total amount with VAT
  - cbc:PayableAmount - Amount due for payment
- cac:InvoiceLine - INVOICE LINE
  - cbc:ID - Invoice line identifier
  - cbc:InvoicedQuantity - Invoiced quantity
  - cbc:LineExtensionAmount - Invoice line net amount
  - cac:Item - ITEM INFORMATION
    - cbc:Name - Item name
    - cac:ClassifiedTaxCategory - LINE VAT INFORMATION
      - cbc:ID - Invoiced item VAT category code
  - cac:Price - PRICE DETAILS
    - cbc:PriceAmount - Item net price
 
Removing the repeated fields and the prices that can be automatically calculated, we end up with:
- Invoice number
- Invoice type code
- Invoice currency code
- Supplier
  - Seller electronic address
  - SELLER POSTAL ADDRESS
  - Seller name
- Customer
  - Buyer electronic address
  - BUYER POSTAL ADDRESS
  - Buyer name
- VAT amount
- Invoice lines
  - Invoiced quantity
  - Item name
  - Invoiced item VAT category code
  - Item net price

Here, the user will have to manually calculate the VAT amount and enter it as an input field. I am also confused about the invoice number. Can we auto generate it? For example based on the date time of the time the invoice is issued.

**Comment by yasharpm** [comment]
@michielbdejong what do you think? Is the invoice format I came up with, sound? Can we actually auto generate the invoice number as well? It has to be an incremental number.

**Comment by michielbdejong** [comment]
> the user will have to manually calculate the VAT amount and enter it as an input field.

Yes, I think that's fine.

>  Can we auto generate the invoice number

Yes, I would say generate one as `YYYY00i` (so in 2023 you would generate 2023001, 2023002, ,etc) but make it editable. Many people use some special custom format to assign invoice numbers.

**Comment by michielbdejong** [comment]
As an example, the Ponder Source foundation uses `S-YY-PPP-0i` where YY are the last two digits and PPP is a product code. For instance yesterday i sent an invoice for the "SURF Research Drive - SRAM integration" project (project code SRS), and it was for book year 2022, so the invoice ID was `S-22-SRS-01`. The next invoice for that project will be `S-23-SRS-01`, then `S-23-SRS-02`, etc.

**Comment by yasharpm** [comment]
Thank you for the feedback! As for what Ponder Source uses, I think it is not compatible with the UBL standard. As they call it "Invoice number" and the description goes as follows:
> A unique identification of the Invoice. The sequential number required in Article 226(2) of the directive 2006/112/EC [2], to uniquely identify the Invoice within the business context, time-frame, operating systems and records of the Seller. No identification scheme is to be used.
My take is that only digits are allowed in the invoice number. See [here](https://docs.peppol.eu/poacc/billing/3.0/syntax/ubl-invoice/cbc-ID/)

**Comment by michielbdejong** [comment]
Ah, interesting! We'll have to switch to a different schema then :)
