### ISSUE TITLE
Find the XSD for AS4 

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/peppol-php#17]
Is this the WSDL for AS4, maybe?
http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/profiles/AS4-profile/v1.0/cs02/AS4-profile-v1.0-cs02.html

**Comment by michielbdejong** [comment]
Ah maybe EBMS has a WSDL, and AS4 is a profile of EBMS?
https://github.com/MartinMulder/ebmsadapter/blob/master/src/main/resources/nl/clockwork/mule/ebms/wsdl/ebms.wsdl

**Comment by phax** [comment]
AS4 ist sent via REST - no WSDL. Only XSD

**Comment by michielbdejong** [comment]
That helps a lot, thanks!
Some more info found here:
"AS4 is based on SOAP and Web Services"
https://blog.axway.com/amplify-products/api-management/what-is-as4

**Comment by michielbdejong** [comment]
So, we found the XSD for AS4, closing this issues. :)
