### ISSUE TITLE
The problem with Soap client and Soap server connection via HTTP

### ISSUE THREAD

**Issue by ishifoev** [pondersource/peppol-php#18]
````
Uncaught SoapFault exception: [HTTP] Error Fetching http headers 
`````

**Comment by ishifoev** [comment]
You can connect via CLI, but it is not working via HTTP. For example, you need getName from the server you can configure it and the client send a request to the server and get information.

**Comment by ishifoev** [comment]
I can say that I have two examples one with WSDL and one without and both works via CLI.

**Comment by ishifoev** [comment]
Need more read about SOAP client and Soap Server here
https://www.php.net/manual/en/class.soapclient.php
https://www.php.net/manual/en/class.soapserver.php

**Comment by ishifoev** [comment]
@phax THank you, yeah I see need some rules before sending request. 

`````
mple:

<eb:PartInfo href="cid:attachment1234@example.com" >
   <eb:PartProperties>
          <eb:Property name="MimeType">application/xml</eb:Property>
          <eb:Property name="CharacterSet">utf-8</eb:Property>

       <eb:Property name="CompressionType">application/gzip</eb:Property>
   </eb:PartProperties>

<eb:PartInfo>

````

**Comment by phax** [comment]
Yes, compression is optional but recommended in Peppol. Depending on the compression used or not, the property shown needs to change
